### PR TITLE
Add Romanian locale

### PR DESCRIPTION
**Pull request by herodrigues**
Continued work from https://github.com/foretagsplatsen/numbro/pull/161

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
you should have rebased your branch on top of `develop` instead of merging it.

Could you please propose a PR without merge commits?

**Comment by herodrigues** [comment]
Fixed 👍

**Comment by BenjaminVanRyseghem** [comment]
Thanks 👍

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.10.0

**Pull request merged**
