### PR TITLE
Add currency code for all cultures codes

### PR DESCRIPTION
**Pull request by herodrigues**
Add currency code for all cultures codes. Reference for symbols: http://www.xe.com/symbols.php

See example in issue #298

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Here is the ISO wikipedia page: https://en.wikipedia.org/wiki/ISO_4217#Active_codes

**Comment by BenjaminVanRyseghem** [comment]
could you add a test (or more) for this please?

**Comment by herodrigues** [comment]
Sure :)

**Comment by ArmorDarks** [comment]
Cool!

As turned out, ISO 4217 is exactly according to BCP 47!

BCP 47 declares extension (Unicode extension), which allows to define currencies, and currency should be exactly ISO 4217. See [specs](http://www.unicode.org/reports/tr35/#u_Extension).

Also some additional info (see Extensions section): https://en.wikipedia.org/wiki/IETF_language_tag

**Comment by herodrigues** [comment]
@ArmorDarks great! Could you help me with that? I mean, I just need someone else to go through language files and check if all currency codes are correct.

**Comment by BenjaminVanRyseghem** [comment]
Thanks 👍

**Comment by BenjaminVanRyseghem** [comment]
I merged it, but we forgot to change `en-US` in `numbro.js:38`

**Comment by herodrigues** [comment]
@BenjaminVanRyseghem I could have sent another commit.

**Comment by BenjaminVanRyseghem** [comment]
@herodrigues I will fix that up before releasing (if I don't forget :smile:)

**Pull request merged**
