### PR TITLE
Correct Polish currency symbol

### PR DESCRIPTION
**Pull request by Graham42**
Edit: further reading found that Latvia, Estonia, and Netherlands have switched to the Euro

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Looks good, but can't be merged :wink

**Comment by Graham42** [comment]
Should be able to merge now?

**Comment by BenjaminVanRyseghem** [comment]
Thanks :+1:

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.2.0

**Pull request merged**
