### PR TITLE
Added zh-HANS localization

### PR DESCRIPTION
**Pull request by gwynjudd**
:warning:

this is based on top of #255

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
shouldn't the code be

- zh-CN for Simplified Chinese
- zh-TW for Traditional Chinese

as said [here](https://github.com/foretagsplatsen/numbro/issues/238#issuecomment-289520442)?

**Comment by ArmorDarks** [comment]
Technically, based on my explaining in https://github.com/foretagsplatsen/numbro/pull/255#issuecomment-289904700, this can be allowed.

However, on practice it is redundant, because in most cases it is common practice to specify those locales with `zh-CN` and `zh-TW`, since they already completely and specifically describes which one is Simplified, and which one is Traditional, based on country code. `zh-Hans-CN` and `zh-Hant-TW` would be technically correct too, but unnecessarly repeating same thing.

Also worth to mention, that `zh-Hans` and `zh-Hant` are _language codes_, not locales, and for l10n files it is more preferable to specify locales.

**Comment by ArmorDarks** [comment]
Yeah, one more thing. Actually, we can use `zh-Hans-CN` and `zh-Hant-TW` too, but only if we will implement loose matching (or kinda aliases?), so that

```js
numbro.setCulture('zh-Hans-CN`)
numbro.setCulture('zh-CN`)
```

would be same thing. This will allow to handle edgy cases, when users decides to specify very exact locale, and we actually can provide it, but it's just named "slightly" differently.

Note that loose matching might be slightly more complicated with some other locales. For instance, when user specifies `sr-CS` (which can be `sr-Latn-CS` or `sr-Cyrl-CS`), we can't know which exactly variant did he meant. However, we can set for one of them higher priority. For instance, currently Serbia usually uses latin version, and cyrillic variant is just a legacy of old times, so we can serve `sr-Latn-CS` for `sr-CS`.

**Comment by ArmorDarks** [comment]
Hey, if we really want to keep this not as locale, but just as a language code, it should be renamed to `zh-Hans`, not `zh-HANS`. But as I've already mentioned few times, it isn't good idea to keep just language codes in l10n files, better to use full locales.

**Comment by ArmorDarks** [comment]
Just as a side note, to avoid confusion, _in some cases_ locale which consists only from language code are valid, like `ru` (because it's `ru-RU`, same thing). In most cases this applies to locales, which doesn't have variants. For instance, `ru` doesn't have variations on contrary to Chinese. So GNU and Unix systems allows such locales. However, it is hard to find standardized list of "locales which may consists only from language codes", and because of that it might be better to prefer full locales and loosely match them.

Specifically regarding locale in this issue, I never encountered `zh-Hans` as a standalone locale. Usually it's language code with country code.

**Comment by BenjaminVanRyseghem** [comment]
@ArmorDarks 
> "locales which may consists only from language codes"

Isn't that what [ISO-639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) is about?

**Comment by BenjaminVanRyseghem** [comment]
@gwynjudd reverted :smile:

**Pull request merged**
