### PR TITLE
Ported languages ko-KR (Korean) and zh-TW (Chinese (Taiwan)) from a numeral.js fork into numbro.js

### PR DESCRIPTION
**Pull request by rocketedaway**
Created tests for languages and updated dist/languages.js and dist/languages.min.js as well.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thank you :)

Could you remove the dist files? :smile:
They will be generated when we release

**Comment by rocketedaway** [comment]
@BenjaminVanRyseghem  Will do.

**Comment by rocketedaway** [comment]
@BenjaminVanRyseghem is anything else needed for this pull request?

**Comment by BenjaminVanRyseghem** [comment]
I haven't seen before the new commit

I will review it asap

**Comment by BenjaminVanRyseghem** [comment]
sorry for the delay

**Comment by BenjaminVanRyseghem** [comment]
this PR broke travis, so I reverted the merge

**Comment by BenjaminVanRyseghem** [comment]
after further investigation, it's not because of your PR.

So I will fix the `develop` branch then try again

**Comment by BenjaminVanRyseghem** [comment]
It should be there. Could you double check? :smile:

Thanks in advance :+1:

**Comment by rocketedaway** [comment]
Looks good :+1:  Thanks!

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.7.0

**Comment by rocketedaway** [comment]
Perfect Thanks!

**Pull request merged**
