### PR TITLE
Allow loading of cultures in node explicitly if numbro hasn't detected correctly that it is in node

### LINKED ISSUE #133: NodeJS is not properly detected
Numbro nodejs runtime detection use a test on process.title : 
```
 (process.title === 'node' || process.title === 'grunt')
```
But in my case it failed because the process.title is /usr/bin/nodejs

Moreover, process.title can be redefined at anytime as it is a read/write property (https://nodejs.org/api/process.html#process_process_title)

I workaround the problem by putting process.title = "node" on startup of my code

### PR DESCRIPTION
**Pull request by stewart42**
fixes #133 and #118

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
thanks for the PR, unfortunately, it doesn't build :smile:

**Comment by stewart42** [comment]
hmm, does on my machine ;)

**Comment by BenjaminVanRyseghem** [comment]
looks like `npm install` fails 👀

**Comment by stewart42** [comment]
```
$ node --version
v0.12.13
$ npm --version
2.15.0
$ nvm --version
0.31.0
31.63s$ npm install 
npm WARN package.json numbro@1.7.0 No license field.
npm WARN peerDependencies The peer dependency grunt@~0.4.2 included from grunt-jscs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@^0.4.1 included from grunt-release will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.13/bin/node" "/home/travis/.nvm/versions/node/v0.12.13/bin/npm" "install"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-confirm@1.0.5 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-bump@0.7.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-release@0.13.0 wants grunt@^0.4.1
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-jscs@1.8.0 wants grunt@~0.4.2
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/foretagsplatsen/numbro/npm-debug.log
```

@BenjaminVanRyseghem  may have to do with the grunt packages being set to `latest` and not being compatible with `node 0.12.13` ?

**Comment by stewart42** [comment]
it might be released to this http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released
`"grunt": ">=0.4.0"`

will issue an PR

**Comment by BenjaminVanRyseghem** [comment]
another idea?

**Comment by stewart42** [comment]
might be better to downgrade grunt back to 0.4.x until the all the dependent grunt packages update

**Comment by stewart42** [comment]
@BenjaminVanRyseghem may be worth saving exact versions for the devDependencies especially if numbro needs to still support old versions of node and npm. 

but for now the build is passing :)

**Comment by BenjaminVanRyseghem** [comment]
sound like a good idea indeed :smile:

Do you mind to squash your latest commits to have a cleaner history? :smile:

**Comment by BenjaminVanRyseghem** [comment]
why?

**Comment by stewart42** [comment]
Apologies got sidetracked

**Comment by stewart42** [comment]
@BenjaminVanRyseghem shout if you need anything further on this

**Comment by BenjaminVanRyseghem** [comment]
Thank you very much 😄

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.7.1

**Pull request merged**
