### PR TITLE
Fix #190 Allow abbreviation precision for < 4

### LINKED ISSUE #190: Fixed precision for average
I saw the average formatter lets you specify precision when the number gets rounded up, but I have commonly had the use case where I want a fixed precision of 3 digits no matter what the number was and whether it was rounded or not. 

So numbro(12345).format('3a') would give 12.3k instead of currently 12k

### PR DESCRIPTION
**Pull request by chrisnicola**
Currently for some reason when using abbreviations like `'0,0a`  you can't specify the number of visible digits of precision for any value less than 4. So while `'4,0a'` will change `1234567` to `1,234k` the result of `'3,0a'` is `1m` instead of `1.23m` as expected.

This is simply caused by a conditional that skips setting the precision in the formatting.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Could you please rewrite you git history? :smile:

**Comment by chrisnicola** [comment]
@BenjaminVanRyseghem I'm assuming you mean squash? I thought Github did that now for you when merging. https://github.com/blog/2141-squash-your-commits

Happy to do it myself, just figured it was easier to let the tooling do it.

**Comment by BenjaminVanRyseghem** [comment]
I do not want to be the one having to find a good message commit for the squashed commit :smile:

**Comment by chrisnicola** [comment]
@BenjaminVanRyseghem all squashed and cleaned up. Let me know if it is good to go.

**Comment by BenjaminVanRyseghem** [comment]
thanks! 👍

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.10.0

**Pull request merged**
