### PR TITLE
Add locales en-AU and en-NZ

### PR DESCRIPTION
**Pull request by Ben305**
This PR adds the locales en-AU and en-NZ

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thank you :smile:

**Comment by Ben305** [comment]
@BenjaminVanRyseghem Wow, that was fast :-) When can we expect to see this on NPM?

**Comment by BenjaminVanRyseghem** [comment]
I can try to do a release today :smile:

remind me if I forget :wink:

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.9.0

**Pull request merged**
