### PR TITLE
added en-ZA language

### PR DESCRIPTION
**Pull request by stewart42**

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thanks :smile:

**Comment by stewart42** [comment]
Thanks for keeping this library alive.
Any idea when this change will make it into a release?

**Comment by BenjaminVanRyseghem** [comment]
It's in my todo list to do a release

So hopefully somewhen this week :smile: 

Do you need it earlier?

**Comment by stewart42** [comment]
Not that urgent, so when you ready is cool. I just wanted to know if it was weeks or months away from being released. If it is this week that would be awesome.

**Comment by BenjaminVanRyseghem** [comment]
ok :smile: 

Now that I said that, I better have to do it :stuck_out_tongue:

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.2.0

**Comment by stewart42** [comment]
Thanks man

**Pull request merged**
