### PR TITLE
Add de-AT localization

### PR DESCRIPTION
**Pull request by gwynjudd**
I have a number of other localizations available, but I just want to see if I can get everything right with this one as a test before working on the others. It is translated from a localization we did for numeral.js so I want to look out for anything missing there.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
why 2 commits with the same short description?

**Comment by gwynjudd** [comment]
That was my mistake I should have squashed the commits together. I'll have to fix it up on Monday when I get in to work.

When I submit a localisation in not sure what bits are required, is it enough just the languages/xx.js and the tests/languages/xx.js?

**Comment by BenjaminVanRyseghem** [comment]
the file + tests should be enough (as we dist for releases)

Now, if you provide a dist, it can potentially be used by people using bleeding-edge :smile:

**Comment by gwynjudd** [comment]
Ok I'll keep that in mind for next time

**Pull request merged**
