### PR TITLE
Fixing large number behavior of format

### LINKED ISSUE #106: Exception on large number formatting
On large numbers (>1e21), `.toFixed` does not actually format in a fixed point manner, but instead leaves the number in scientific notation.

So `numbro(1e22).format("0.00")` does this:
```
./numbro.js:537
            if (d.split('.')[1].length) {
                               ^
TypeError: Cannot read property 'length' of undefined
    at formatNumber (numbro.js:537:32)
    at formatNumbro (numbro.js:77:22)
    at Object.numbro.fn.Numbro.format (numbro.js:921:20)
    ...
```

### PR DESCRIPTION
**Pull request by andrewla**
Fixes #106

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
it looks like we are using an old version of the code or?
Your fix is good, but you also revert a lot of code :confused:

**Comment by andrewla** [comment]
Yes; bad rebase.  Let me fix up.

**Comment by BenjaminVanRyseghem** [comment]
:+1:

**Comment by andrewla** [comment]
That's much better

**Comment by BenjaminVanRyseghem** [comment]
That I buy :smile:

Thanks

**Comment by andrewla** [comment]
@BenjaminVanRyseghem when do you anticipate cutting another release?

**Comment by BenjaminVanRyseghem** [comment]
somewhere this week, maybe today :smile:

**Comment by andrewla** [comment]
That would be awesome!  Thanks for all your work on this.

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.5.2

**Pull request merged**
