### PR TITLE
Added sr localization

### PR DESCRIPTION
**Pull request by gwynjudd**

### CODE REVIEW

**Comment by ArmorDarks** [comment]
I think it worth to denote this locale as `sr-Cyrl` to show, that it is Cyrillic version.

It is quite crucial, because in Serbia both latin and cyrillic versions are popular, so we can't guess which exactly variation users want.

In fact, it would be even better to write it as `sr-Cyrl-RS`

**Comment by gwynjudd** [comment]
@ArmorDarks done

**Comment by ArmorDarks** [comment]
Omg, what happened with commits in this PR? I even don't see your original commit anymore

**Comment by gwynjudd** [comment]
@ArmorDarks I'm not sure, I renamed sr to sr-Cyrl-RS and I'm trying to rebase my branch against develop and this happened. If I can't fix it up I may just close this and redo it

**Pull request closed without merging**
