### PR TITLE
Add culture function, deprecate language

### PR DESCRIPTION
**Pull request by wereHamster**

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
thanks

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.8.0

**Comment by MarkAPhillips** [comment]
Hi can the docs on the site be updated to reflect this change - thanks as still currently refers to 
`numbro.language('fr-FR');`  and not

`numbro.culture('fr-FR');` 

for example

**Comment by BenjaminVanRyseghem** [comment]
sure it can :smile:

it just require time, or a helpful PR :smile:

can you create a dedicated ticket for it please?

**Pull request merged**
