### PR TITLE
Fix fr-CA currency format

### PR DESCRIPTION
**Pull request by killfish**

### CODE REVIEW

**Comment by killfish** [comment]
The test suite passes for my locally -- I'm not sure why it fails when it goes through the build process...

**Comment by BenjaminVanRyseghem** [comment]
```
format - numbers...ERROR
>> Message: +0
>> Error: '' === '0'
>> at Object.strictEqual (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/types.js:83:39)
>> at Object.exports.format.numbers (tests/numbro/format.js:147:18)
>> at Object.<anonymous> (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/core.js:236:16)
>> at Object.<anonymous> (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/core.js:236:16)
>> at /home/travis/build/foretagsplatsen/numbro/node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/core.js:236:16
>> at Object.exports.runTest (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/core.js:70:9)
>> at /home/travis/build/foretagsplatsen/numbro/node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/core.js:118:25
>> at /home/travis/build/foretagsplatsen/numbro/node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/deps/async.js:513:13
>> at iterate (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/deps/async.js:123:13)
>> at /home/travis/build/foretagsplatsen/numbro/node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/deps/async.js:134:25
```

for iojs

**Comment by killfish** [comment]
I'm using node 4.0.0 locally. Do I need to run the tests using iojs?

**Comment by BenjaminVanRyseghem** [comment]
it looks like it's on this runtime the test fails.

**Comment by BenjaminVanRyseghem** [comment]
in numbro 1.8.0

**Pull request merged**
