### PR TITLE
changed to "." for k-separator

### PR DESCRIPTION
**Pull request by gka**
the thousand separator in Germany is definitely the dot, and not the space.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thanks for the PR :+1: 

Could you please fix the tests before I can merge it? :smile:

**Comment by BenjaminVanRyseghem** [comment]
On the other hand, the international system advocates the use of a space, see [here](https://en.wikipedia.org/wiki/ISO_31-0#Numbers)

**Comment by BenjaminVanRyseghem** [comment]
@gka what should we do with this PR?

**Comment by gka** [comment]
Not sure about the international system advocates, but I lived in Germany for 30 years and haven't seen the space used a single time. Seriously, the space is not used in Germany. Never. That's a Swiss thing.

**Comment by BenjaminVanRyseghem** [comment]
Ok :smile: 

Could you at least fix the tests?

**Comment by gka** [comment]
yes, I'm on it.

**Comment by BenjaminVanRyseghem** [comment]
Cool :smile: 

Thanks

**Comment by gka** [comment]
tests are passing now in my patch branch

**Comment by BenjaminVanRyseghem** [comment]
ok, and can you make the branch mergeable please?

**Comment by gka** [comment]
created a new PR under #73

**Comment by BenjaminVanRyseghem** [comment]
why creating a new pr?

**Comment by gka** [comment]
b/c it was easier for me to re-commit the changes from a fresh fork than merging/rebasing my numbro fork to your upstream. after all I have no idea about the rest of numbros codebase, and I don't want to get into it right now.

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.5.1

**Pull request closed without merging**
