### PR TITLE
Fix usage in Node ES6 whereby `this` is sometimes undefined

### PR DESCRIPTION
**Pull request by hiddentao**
I was getting the following error when using this in a server-side React app:

```
TypeError: Cannot set property 'numbro' of undefined
    at /Users/ram/dev/clients/bananas/homenature/node_modules/numbro/numbro.js:1215:20
    at Object.<anonymous> (/Users/ram/dev/clients/bananas/homenature/node_modules/numbro/numbro.js:1225:3)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/ram/dev/clients/bananas/homenature/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ram/dev/clients/bananas/homenature/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ram/dev/clients/bananas/homenature/src/frontend/js/data/models/product.js:1:23)
    at Module._compile (module.js:460:26)
    at normalLoader (/Users/ram/dev/clients/bananas/homenature/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ram/dev/clients/bananas/homenature/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

This fix ensures that if `module.exports` is available then the other exposure methods don't need to be used.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Tests are not running :smile:

**Comment by hiddentao** [comment]
Hmm, looks like it was a connectivity issue in Travis -> https://travis-ci.org/foretagsplatsen/numbro/jobs/93867275

Is there a quick way I can trigger a re-run without a commit?

**Comment by BenjaminVanRyseghem** [comment]
I restarted it :smile:

**Comment by BenjaminVanRyseghem** [comment]
your PR can't be merged :smile:

Could you have a look please?

**Comment by hiddentao** [comment]
Done.

**Comment by BenjaminVanRyseghem** [comment]
it looks like still not :smile:

I was not expecting you to be that fast :smile:
Sorry for the loos

**Comment by hiddentao** [comment]
Should be good now.

**Comment by BenjaminVanRyseghem** [comment]
:+1:

**Pull request merged**
