### PR TITLE
Add Romanian locale

### PR DESCRIPTION
**Pull request by andreialecu**

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
can you rebase on the latests `develop`? It should fix the travis issue

**Comment by herodrigues** [comment]
Since @andreialecu has not answered, I just open another PR to rebase these changes.

**Comment by andreialecu** [comment]
I don't see a travis issue here btw.

**Comment by herodrigues** [comment]
@andreialecu you can't see cause I fixed it, but there was a travis issue 😄

**Pull request closed without merging**
